Implement Redux
HtetNaing0814/Bookstore pull request #2
Opened 2022-08-15 17:22 UTC by HtetNaing0814

- Added Redux Toolkit(npm install react-redux @reduxjs/toolkit).

- Structured application files using a "feature folder" approach and use the [ducks pattern](https://github.com/erikras/ducks-modular-redux) for Redux files. Files/Folder structure look exactly like the structure given in the requirements:

- Wrote book's actions and reducer (in /src/redux/books/books.js) using the [ducks pattern](https://github.com/erikras/ducks-modular-redux).

- Defined action types for adding and removing a book.
  - Set the initial state to be an empty array of books.
  - Exported Action Creators for my actions.
  - Wrote my reducer and exported it as default.
  - Defined state changes for the actions that I created.
  - In case of unknown action - return the current state.
  - Wrote my categories actions and reducer (in /src/redux/categories/categories.js) using the [ducks pattern](https://github.com/erikras/ducks-modular-redux).

- Define an action type for checking the status.
  - Set the initial state to be an empty array of categories.
  - Exported Action Creators for your actions.
  - Wrote your reducer and exported it as default.
  - For the check status action return a string "Under construction".
  - In case of unknown action - return the current state.
  - Configure the Redux Store (/src/redux/configureStore.js):

- Imported the necessary methods from Redux Toolkit.
- Combined both reducers into a root reducer by using the configureStore function.

2022-08-15 17:45 UTC, TedLivist requested changes
## STATUS: CHANGES REQUIRED ♻️ ♻️

Hi @HtetNaing0814,

Good job so far!
✔️ Good documentation
✔️ Implementation of redux store
However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-15 17:45 UTC, TedLivist commented on src/redux/books/books.js
> +      // state.filter((book) => book.id !== action.index);
- [ ] Kindly remove this commented code as it can makes your code hard to read and maintain.

2022-08-15 17:45 UTC, TedLivist commented on src/redux/books/books.js
> +
- [ ] In keeping the ducks pattern kindly refactor these action types.

  ```
  const ADD_BOOK = 'bookstore/books/ADD_BOOK'
  const REMOVE_BOOK = 'bookstore/books/REMOVE_BOOK'
  ```

  You read [this article for more](https://medium.com/@matthew.holman/what-is-redux-ducks-46bcb1ad04b7)

2022-08-15 17:45 UTC, TedLivist commented on src/redux/categories/categories.js
> +const STATUS = 'UNDER_CONSTRUCTION';
- [ ] Kindly refactor to duck's pattern.

  ```
  CHECK_STATUS = 'bookstore/categories/CHECK_STATUS'
  ```

2022-08-15 17:45 UTC, TedLivist commented on src/redux/books/books.js
> +const booksXer = (state = [{ id: '1', title: 'Elden Ring', author: 'Miyazaki' }, { id: '2', title: 'One Piece', author: 'Eichiro Oda' }], action) => {
- [ ] Initial states should be defined as a stand-alone variables. This is good for situations like this where you want to initialize your state to something. It gets messy doing so in the reducer arguments as you can see.

  Kindly define an initial state and set the state to the initial state.
  ```
  const initialState = []
  ...
  const booksXer = (state = initialState, action) => {
    ...
  ```

2022-08-15 17:45 UTC, TedLivist commented on src/redux/books/books.js
> +    case REMOVE:
- [ ] Remember to update your action types here if you changed it from the requested change above.

2022-08-15 17:45 UTC, TedLivist commented on src/redux/categories/categories.js
> +const cateXer = (state = [], action) => {
- [ ] Set an `initialState` as it own variable as demonstarted above in the books file.

2022-08-15 17:45 UTC, TedLivist commented on src/redux/categories/categories.js
> +    case STATUS:
- [ ] Remember to update your action type here if you changed it

2022-08-16 04:00 UTC, ShoiraTa approved these changes
## **STATUS: APPROVED  🟢 ** 
------
### Hi @HtetNaing0814 , 

**Great work on making the changes requested by a previous reviewer 👏🏻** 

Your project is complete! . There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

![5SW](https://user-images.githubusercontent.com/77038610/154919611-7d0675af-6364-45a3-92d6-eccd9b743ced.gif)

**Cheers and Happy coding! :clap: :clap: :clap:**

Feel free to leave any questions or comments in the PR thread by mentioning my Github username if something is not 100% clear.
***
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have  limited number of  reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-16 04:11 UTC, merged